_core:
  default_config_hash: RePADAH4yHzDAKh-gEsDxPFK9hQe32l4p4t8Cqryww8
langcode: en
name: DrupalCamp
mail: test@example.com
slogan: 'A blogging profile for Tome users'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
uuid: b4faeaa2-5035-4891-bc7a-83f10f0a08a6
